# Generated by Django 5.1.1 on 2024-10-04 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pirate', '0001_initial'),
        ('Ship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pirate',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='pirate',
            name='ship_name',
        ),
        migrations.AddField(
            model_name='pirate',
            name='ship',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Ship.ship'),
            preserve_default=False,
        ),
    ]
