# Generated by Django 5.1.1 on 2024-10-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pirate', '0003_alter_pirate_ship'),
        ('Ship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pirate',
            name='ship',
        ),
        migrations.AddField(
            model_name='pirate',
            name='Ship',
            field=models.ManyToManyField(blank=True, to='Ship.ship'),
        ),
    ]
