# Generated by Django 5.1.1 on 2024-09-28 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ability', '0001_initial'),
        ('Arc', '0001_initial'),
        ('Bounty', '0001_initial'),
        ('DevilFruit', '0001_initial'),
        ('Faction', '0001_initial'),
        ('Haki', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('dead ', 'Dead'), ('unknwon', 'Unknown')], max_length=10)),
                ('age', models.IntegerField()),
                ('race', models.CharField(choices=[('human', 'Human'), ('fishmen', 'Fishman')], default='Human', max_length=30)),
                ('birthday', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('abilitys', models.ManyToManyField(to='Ability.ability')),
                ('arcs', models.ManyToManyField(to='Arc.arc')),
                ('bountys', models.ManyToManyField(to='Bounty.bounty')),
                ('devil_fruits', models.ManyToManyField(to='DevilFruit.devilfruit')),
                ('factions', models.ManyToManyField(to='Faction.faction')),
                ('hakis', models.ManyToManyField(to='Haki.haki')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
            ],
        ),
    ]
