# Generated by Django 5.1.1 on 2024-10-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ability', '0002_alter_ability_description'),
        ('Arc', '0001_initial'),
        ('Character', '0004_alter_character_marine_alter_character_pirate'),
        ('DevilFruit', '0003_remove_devilfruit_awakened_and_more'),
        ('Faction', '0003_remove_faction_current_faction_and_more'),
        ('Haki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ability',
            field=models.ManyToManyField(blank=True, to='Ability.ability'),
        ),
        migrations.AlterField(
            model_name='character',
            name='arc',
            field=models.ManyToManyField(blank=True, to='Arc.arc'),
        ),
        migrations.AlterField(
            model_name='character',
            name='birthday',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='devil_fruit',
            field=models.ManyToManyField(blank=True, to='DevilFruit.devilfruit'),
        ),
        migrations.AlterField(
            model_name='character',
            name='faction',
            field=models.ManyToManyField(blank=True, to='Faction.faction'),
        ),
        migrations.AlterField(
            model_name='character',
            name='haki',
            field=models.ManyToManyField(blank=True, to='Haki.haki'),
        ),
    ]
