# Generated by Django 5.1.1 on 2024-09-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevilFruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('df_name', models.CharField(max_length=20)),
                ('df_jp_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('current_owner', models.BooleanField(default=True)),
                ('awakened', models.BooleanField()),
            ],
        ),
    ]
