# Generated by Django 5.1.1 on 2024-10-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevilFruit', '0002_alter_devilfruit_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devilfruit',
            name='awakened',
        ),
        migrations.RemoveField(
            model_name='devilfruit',
            name='current_owner',
        ),
    ]
