# Generated by Django 5.1.1 on 2024-09-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=20)),
                ('faction_name', models.CharField(max_length=20)),
                ('current_faction', models.BooleanField(default=True)),
            ],
        ),
    ]
