# Generated by Django 5.1.1 on 2024-10-01 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='rank',
        ),
    ]
