# Generated by Django 5.1.1 on 2024-10-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faction', '0002_remove_faction_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='current_faction',
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction_name',
            field=models.CharField(max_length=30),
        ),
    ]
