# Generated by Django 5.1.1 on 2024-09-28 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sea.sea')),
            ],
        ),
    ]
