# Generated by Django 5.1.1 on 2024-10-01 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bounty', '0001_initial'),
        ('Character', '0002_remove_character_bountys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='char_id',
        ),
        migrations.AddField(
            model_name='bounty',
            name='character',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Character.character'),
            preserve_default=False,
        ),
    ]
